import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useEffect } from 'react';

declare global {
  namespace JSX {
    interface IntrinsicElements {
      ['todo-list']: React.DetailedHTMLProps<React.HTMLAttributes<HTMLElement>, HTMLElement>,
      ['chain-reaction']: React.DetailedHTMLProps<React.HTMLAttributes<HTMLElement>, HTMLElement>
    }
  }
}

const Home: NextPage = () => {
  useEffect(() => {
    import('../litComponents/todo-list')
    import('../litComponents/chain-reaction')
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main style={{textAlign: 'center'}}>
        <h2>testing</h2>
        <todo-list></todo-list>
        <chain-reaction></chain-reaction>
      </main>

    </div>
  )
}

export default Home
