import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Link  from 'next/link';

declare global {
  namespace JSX {
    interface IntrinsicElements {
      ['todo-list']: React.DetailedHTMLProps<React.HTMLAttributes<HTMLElement>, HTMLElement>,
      ['chain-reaction']: React.DetailedHTMLProps<React.HTMLAttributes<HTMLElement>, HTMLElement>
    }
  }
}

const Home: NextPage = () => {

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main style={{textAlign: 'center'}}>
        <h2>testing</h2>
        <Link href="/todo">
        <button type="button">Todo</button>
        </Link>
        <Link href="/chain-reaction">
          <button type="button">Chain Reaction</button>
        </Link>
      </main>

    </div>
  )
}

export default Home
